API Updates
stripe/stripe-go pull request #1332
Opened 2021-08-31 22:02 UTC by richardm-stripe

Codegen for openapi 944e56f.
r? @dcr-stripe
cc @stripe/api-libraries

## Changelog
* Add support for `AfterExpiration`, `ConsentCollection`, and `ExpiresAt` on `CheckoutSessionParams` and `CheckoutSession`
* Add support for `Consent` and `RecoveredFrom` on `CheckoutSession`

2021-08-31 22:12 UTC, remi-stripe requested changes

2021-08-31 22:12 UTC, remi-stripe commented on client/api.go
> +	"github.com/stripe/stripe-go/v72/lineitem"
this addition seems incorrect

2021-08-31 22:12 UTC, richardm-stripe commented on client/api.go
> +	"github.com/stripe/stripe-go/v72/lineitem"
```suggestion
```

2021-08-31 22:14 UTC, richardm-stripe commented on client/api.go
> +	"github.com/stripe/stripe-go/v72/lineitem"
Yes, codegen bug I need to fix.

2021-08-31 22:14 UTC, remi-stripe approved these changes

2021-09-01 00:02 UTC, remi-stripe approved these changes

2021-09-01 02:28 UTC, merged