API Updates
stripe/stripe-go pull request #1451
Opened 2022-04-14 21:45 UTC by richardm-stripe

Codegen for openapi 9e8cdc3.
r? @kamil-stripe
cc @stripe/api-libraries

## Changelog
* Change type of `FundingInstructionsBankTransferFinancialAddressesSupportedNetworks` and `PaymentIntentNextActionDisplayBankTransferInstructionsFinancialAddressesSupportedNetworks` from `literal('zengin')` to `enum('sepa'|'zengin')`
* Change type of `FundingInstructionsBankTransferFinancialAddressesType` and `PaymentIntentNextActionDisplayBankTransferInstructionsFinancialAddressesType` from `literal('zengin')` to `enum('iban'|'zengin')`
* Change type of `FundingInstructionsBankTransferType` from `literal('jp_bank_transfer')` to `enum('eu_bank_transfer'|'jp_bank_transfer')`

2022-04-15 03:49 UTC, kamil-stripe approved these changes

2022-04-18 18:54 UTC, dcr-stripe requested changes

2022-04-18 18:54 UTC, dcr-stripe commented on example/generated_examples_test.go
> +		BankTransfer: &stripe.CustomerBankTransferParams{
Need to fix this to include the custom method name (ie. it should be `CustomerCreateFundingInstructionsBankTransferParams`)

2022-04-18 18:54 UTC, dcr-stripe commented on fundinginstructions.go
> +	FundingInstructionsBankTransferTypeJpBankTransfer FundingInstructionsBankTransferType = "jp_bank_transfer"
EU and JP should be capitalized here.

2022-04-18 18:54 UTC, dcr-stripe commented on paymentintent.go
> +	PaymentIntentNextActionDisplayBankTransferInstructionsTypeJpBankTransfer PaymentIntentNextActionDisplayBankTransferInstructionsType = "jp_bank_transfer"
Same comment here for JP

2022-04-18 18:54 UTC, dcr-stripe commented on paymentintent.go
> +	PaymentIntentPaymentMethodOptionsCustomerBalanceBankTransferTypeUSBankTransfer PaymentIntentPaymentMethodOptionsCustomerBalanceBankTransferType = "us_bank_transfer"
We should fix the capitalizations here to be consistent

2022-04-18 18:54 UTC, dcr-stripe commented on terminal_configuration.go
> +type TerminalConfigurationTippingAudParams struct {
Need to fix these capitalizations to be consistent.

2022-04-19 01:19 UTC, kamil-stripe approved these changes

2022-04-19 13:11 UTC, dcr-stripe approved these changes
LGTM

2022-04-19 17:26 UTC, merged